### ISSUE TITLE
feature request: add a cmake install target

### ISSUE THREAD

**Issue by ehaupt** [jorio/CandyCrisis#1]
For packaging it would be great to have an install target.

**Comment by alexmyczko** [comment]
once this is fixed, http://sid.ethz.ch/debian/candycrisis gets a thing

**Comment by ehaupt** [comment]
> once this is fixed, sid.ethz.ch/debian/candycrisis gets a thing

Very cool. Love the game by the way.

**Comment by jorio** [comment]
Check out branch [install-target](https://github.com/jorio/CandyCrisis/tree/install-target).

The game is installed in `(prefix)/bin/candycrisis` and its data in `(prefix)/share/candycrisis`.

Let me know if that's fine for packaging. If it is, I'll merge this into master.

**Comment by ehaupt** [comment]
Thank you, that works fine on FreeBSD.

Maybe also install the desktop icon `candycrisis-desktopicon.png` as `candycrisis.png`.

Plus a `candycrisis.desktop` would be nice. I am manually installing this one with the FreeBSD port. Feel free to use it:

```
[Desktop Entry]
Type=Application
Version=1.0
Name=Candy Crisis
GenericName=An exciting combination of pure action and puzzle gaming!
Comment=An exciting combination of pure action and puzzle gaming!
Icon=candycrisis
Exec=candycrisis
Categories=Game;
```

Implementing those will allow me to drop a lot of extra glue in the the [FreeBSD port](https://github.com/freebsd/freebsd-ports/blob/main/games/candycrisis/Makefile).

**Comment by jorio** [comment]
Try the latest commit on branch install-target - it installs an XDG desktop file and an icon.

**Comment by ehaupt** [comment]
> Try the latest commit on branch install-target - it installs an XDG desktop file and an icon.

Works like a charm. Thank you.

**Comment by jorio** [comment]
Great! I'll merge that into master and tag it as version 3.0.1 in the coming days.

**Comment by ehaupt** [comment]
Perfect, thank you. I'll update the FreeBSD port once it's tagged.

**Comment by jorio** [comment]
[v3.0.1 is tagged!](https://github.com/jorio/CandyCrisis/releases/tag/v3.0.1)

**Comment by ehaupt** [comment]
FreeBSD port updated.
